/* 
 * Betfair: Exchange Streaming API
 *
 * API to receive streamed updates. This is an ssl socket connection of CRLF delimited json messages (see RequestMessage & ResponseMessage)
 *
 * OpenAPI spec version: 1.0.1423
 * Contact: bdp@betfair.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package swagger

type MarketSubscriptionMessage struct {

	// The operation type
	Op string `json:"op,omitempty"`

	// Client generated unique id to link request with response (like json rpc)
	Id int32 `json:"id,omitempty"`

	// Segmentation Enabled - allow the server to send large sets of data in segments, instead of a single block
	SegmentationEnabled bool `json:"segmentationEnabled,omitempty"`

	// Token value delta (received in MarketChangeMessage) that should be passed to resume a subscription
	Clk string `json:"clk,omitempty"`

	// Heartbeat Milliseconds - the heartbeat rate (looped back on initial image after validation: bounds are 500 to 5000)
	HeartbeatMs int64 `json:"heartbeatMs,omitempty"`

	// Token value (received in initial MarketChangeMessage) that should be passed to resume a subscription
	InitialClk string `json:"initialClk,omitempty"`

	MarketFilter MarketFilter `json:"marketFilter,omitempty"`

	// Conflate Milliseconds - the conflation rate (looped back on initial image after validation: bounds are 0 to 120000)
	ConflateMs int64 `json:"conflateMs,omitempty"`

	MarketDataFilter MarketDataFilter `json:"marketDataFilter,omitempty"`
}
