/* 
 * Betfair: Exchange Streaming API
 *
 * API to receive streamed updates. This is an ssl socket connection of CRLF delimited json messages (see RequestMessage & ResponseMessage)
 *
 * OpenAPI spec version: 1.0.1423
 * Contact: bdp@betfair.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package swagger

type OrderFilter struct {

	// Returns overall / net position (See: OrderRunnerChange.mb / OrderRunnerChange.ml). Default=true
	IncludeOverallPosition bool `json:"includeOverallPosition,omitempty"`

	// Internal use only & should not be set on your filter (your subscription is already locked to your account). If set subscription will fail.
	AccountIds []int64 `json:"accountIds,omitempty"`

	// Restricts to specified customerStrategyRefs; this will filter orders and StrategyMatchChanges accordingly (Note: overall postition is not filtered)
	CustomerStrategyRefs []string `json:"customerStrategyRefs,omitempty"`

	// Returns strategy positions (See: OrderRunnerChange.smc=Map<customerStrategyRef, StrategyMatchChange>) - these are sent in delta format as per overall position. Default=false
	PartitionMatchedByStrategyRef bool `json:"partitionMatchedByStrategyRef,omitempty"`
}
