/* 
 * Betfair: Exchange Streaming API
 *
 * API to receive streamed updates. This is an ssl socket connection of CRLF delimited json messages (see RequestMessage & ResponseMessage)
 *
 * OpenAPI spec version: 1.0.1423
 * Contact: bdp@betfair.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package swagger

type RunnerChange struct {

	// The total amount matched. This value is truncated at 2dp.
	Tv float64 `json:"tv,omitempty"`

	// Best Available To Back - LevelPriceVol triple delta of price changes, keyed by level (0 vol is remove)
	Batb [][]float64 `json:"batb,omitempty"`

	// Starting Price Back - PriceVol tuple delta of price changes (0 vol is remove)
	Spb [][]float64 `json:"spb,omitempty"`

	// Best Display Available To Lay (includes virtual prices)- LevelPriceVol triple delta of price changes, keyed by level (0 vol is remove)
	Bdatl [][]float64 `json:"bdatl,omitempty"`

	// Traded - PriceVol tuple delta of price changes (0 vol is remove)
	Trd [][]float64 `json:"trd,omitempty"`

	// Starting Price Far - The far starting price (or null if un-changed)
	Spf float64 `json:"spf,omitempty"`

	// Last Traded Price - The last traded price (or null if un-changed)
	Ltp float64 `json:"ltp,omitempty"`

	// Available To Back - PriceVol tuple delta of price changes (0 vol is remove)
	Atb [][]float64 `json:"atb,omitempty"`

	// Starting Price Lay - PriceVol tuple delta of price changes (0 vol is remove)
	Spl [][]float64 `json:"spl,omitempty"`

	// Starting Price Near - The far starting price (or null if un-changed)
	Spn float64 `json:"spn,omitempty"`

	// Available To Lay - PriceVol tuple delta of price changes (0 vol is remove)
	Atl [][]float64 `json:"atl,omitempty"`

	// Best Available To Lay - LevelPriceVol triple delta of price changes, keyed by level (0 vol is remove)
	Batl [][]float64 `json:"batl,omitempty"`

	// Selection Id - the id of the runner (selection)
	Id int64 `json:"id,omitempty"`

	// Handicap - the handicap of the runner (selection) (null if not applicable)
	Hc float64 `json:"hc,omitempty"`

	// Best Display Available To Back (includes virtual prices)- LevelPriceVol triple delta of price changes, keyed by level (0 vol is remove)
	Bdatb [][]float64 `json:"bdatb,omitempty"`
}
